### PR TITLE
Build library using dune

### LINKED ISSUE #8: dune
Could you please switch to dune?

### PR DESCRIPTION
**Pull request by psafont**
Took the time to remove the warnings emitted, updated the opam metadata to follow what's on `opam-repository` and changed where the CI is run as travis is deprecated. Job status can be seen at https://github.com/psafont/ocaml-systemd/actions/runs/3471684067

fixes #8

### CODE REVIEW

**Comment by juergenhoetzel** [comment]
Awesome cleanup: Thanks a lot for your contribution! :+1:

**Comment by psafont** [comment]
With these changes the library can be compiled under ocaml 5 beta 1, would you mind releasing a new version when you can? If you're limited on time you could tag the latest commit and I'd take care of the rest

**Comment by juergenhoetzel** [comment]
> With these changes the library can be compiled under ocaml 5 beta 1, would you mind releasing a new version when you can? If you're limited on time you could tag the latest commit and I'd take care of the rest
:+1: 
Opened PR: https://github.com/ocaml/opam-repository/pull/22536

**Comment by psafont** [comment]
Thanks!

**Pull request merged**
